sudo: false
cache: pip
language: python
python:
  - "3.6"
stages:
  - lint
  - docs
jobs:
  include:
    # lint stage
    - stage: lint
      env: TOXENV=manifest
    - env: TOXENV=flake8
    - env: TOXENV=xenon
    # docs stage
    - stage: docs
      env: TOXENV=doc8
    - env: TOXENV=readme
    - env: TOXENV=docs
matrix:
  allow_failures:
    - env: TOXENV=xenon
install:
  - pip install tox
script:
  - tox
